ExternalConfigs:
  - TRATS-SDK
  - EMULATOR-SDK

Default:
    Baseline: SLP-2.0
    FileSystem: ext4
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: America/Los_Angeles
    RootPass: root
    DefaultUser: root
    DefaultUserPass: ""
    BootloaderOptions: ""

EMULATOR-SDK:
    Part: slp-emulator
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: ia32
    Mic2Options: -f loop --pack-to=@NAME@-@SRNAME@.tar.gz --runtime=bootstrap
    Repos:
        - tizen-base
        - tizen-main

TRATS-SDK:
    Part: trats-arm
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -f loop --pack-to=@NAME@-@SRNAME@.tar.gz
    Repos:
        - tizen-base
        - tizen-main

