ExternalConfigs:
  - Mobile-emulator

Default:
    Baseline: tizen-0.0
    FileSystem: ext4
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: Asia/Seoul
    RootPass: tizen
    DefaultUser: tizen
    DefaultUserPass: tizen
    PartSize: 1900
    BootloaderOptions: ""

Mobile-emulator:
    Part: tizen-emulator
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: ia32
    Mic2Options: -v -d -A i586 -A i686 -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - 2.4-mobile-emulator
        - 2.4-mobile-base-emul
