ExternalConfigs:
  - TV-target

Default:
    Baseline: tizen-0.0
    FileSystem: ext4
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: Asia/Seoul
    RootPass: tizen
    DefaultUser: tizen
    DefaultUserPass: tizen
    PartSize: 1900
    BootloaderOptions: ""

TV-target:
    Part: tv-arm
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -v -d -A armv7l -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - 2.4-tv-target
        - 2.4-base
