ExternalConfigs:
  - TRATS-RSA
  - M0-RSA
  - handset

Default:
    Baseline: tizen-0.0
    FileSystem: ext3
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: America/Los_Angeles
    RootPass: tizen
    DefaultUser: tizen
    DefaultUserPass: tizen
    PartSize: 1900
    BootloaderOptions: ""

Handset:
    PartSize: 1024
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Architecture: ia32
    Desktop: None
    Repos:
        - Tizen-base
        - Tizen-main
TRATS-RSA:
    Part: trats-arm
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - Tizen-main
        - Tizen-base
M0-RSA:
    Part: m0-arm
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - Tizen-main
        - Tizen-base
