ExternalConfigs:
  - Wearable-target-b3
  - Wearable-boot-b3

Default:
    Baseline: tizen-0.0
    FileSystem: ext4
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: Asia/Seoul
#RootPass: tizen
    RootPass: root
    DefaultUser: tizen
    DefaultUserPass: tizen
    PartSize: 1900
    BootloaderOptions: ""

Wearable-target-b3:
    Part: wearable-arm
    Bootloader: True
    BootloaderAppend: "rootdelay=5"
    BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -A armv7l -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - 2.3.1-wearable-target-b3

Wearable-boot-b3:
    Part: wearable-boot-b3
    Bootloader: True
#BootloaderAppend: "rootdelay=5"
#BootloaderTimeout: 0
    SaveRepos:  True
    Desktop: None
    DefaultUser: root
    DefaultUserPass: ""
    Architecture: armv7l
    Mic2Options: -A armv7l -f loop --pack-to=@NAME@.tar.gz
    Repos:
        - 2.3.1-wearable-target-b3
